# .github/workflows/deploy.yml
name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the action on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js (if you are using a static site generator like Jekyll or Hugo)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build site (if needed)
      run: npm install && npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Change this if your static site generator outputs files to a different folder
